
pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
---
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Chaand Patel
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://chaandp.github.io/
#
# 2. URL of this page
url:              http://chaandp.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Chaand Patel  |  Portfolio
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            https://github.com/chaandp
  #
  # URL of a cover photo of your project
  cover_image:    https://img.freepik.com/free-vector/abstract-minimal-white-background_105940-668.jpg?size=626&ext=jpg&ga=GA1.2.1699440138.1595721600
  #
  # Use a one-liner to describe your project
  description:    Data Analyst  |  Data Engineer  |  Data Scientist
  
 ---
 
 <style type="text/css">

h1.title {
  font-size: 38px;
  color: DarkRed;
  text-align: center;
}
h4.name { /* Header 4 - and the author and data headers use this too  */
    font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkRed;
  text-align: center;
}
h4.description { /* Header 4 - and the author and data headers use this too  */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
  text-align: center;
}
</style>

#
# 4. Your Twitter handle
twitter_handle:   StairRover
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  My name is Chaand Patel and I am a recent graduate from Rutgers University with a Bachelor of Science in Computer Science with a minor in Critical Inteligence Studies. I have a great interest in the application of data and technology to promote growth and tackle initiatives geared towards understanding the emerging needs of customers. I am a highly motivated individual with a passion for intellectual challenges and data-driven innovation. Currently, I am actively seeking a full-time position in the field of computer science that challenges my skill set as well as broadens my opportunity for growth and would like to welcome the opportunity to connect.